name: Deploy Dev to AppCenter

on:
  push:
    branches: [ version/* ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy to AppCenter
    runs-on: macos-12

    steps:
      - name: Setup Xcode to 14.0.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0.1'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby v3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Setup Rust and Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Lipo via Cargo
        run: cargo install cargo-lipo

      - name: Add iOS targets to Rust
        run: rustup target add aarch64-apple-ios x86_64-apple-ios

      - name: Run Fastlane (build, upload to AppCenter)
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: dev
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_IDENTIFIER_DEV: ${{ secrets.APP_IDENTIFIER_DEV }}
          DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          PROVISIONING_PROFILE_SPECIFIER_DEV: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER_DEV }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
          APP_CENTER_API_TOKEN: ${{ secrets.APP_CENTER_API_TOKEN }}

          XCCONFIG_DEV_INFURA_PROJECT_ID: ${{ secrets.XCCONFIG_DEV_INFURA_PROJECT_ID }}
          XCCONFIG_DEV_INFURA_PROJECT_SECRET: ${{ secrets.XCCONFIG_DEV_INFURA_PROJECT_SECRET }}
          XCCONFIG_DEV_ETHERSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_ETHERSCAN_API_KEY }}
          XCCONFIG_DEV_ARBISCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_ARBISCAN_API_KEY }}
          XCCONFIG_DEV_OPTIMISM_ETHERSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_OPTIMISM_ETHERSCAN_API_KEY }}
          XCCONFIG_DEV_BSCSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_BSCSCAN_API_KEY }}
          XCCONFIG_DEV_POLYGONSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_POLYGONSCAN_API_KEY }}
          XCCONFIG_DEV_SNOWTRACE_API_KEY: ${{ secrets.XCCONFIG_DEV_SNOWTRACE_API_KEY }}
          XCCONFIG_DEV_DEFIYIELD_API_KEY: ${{ secrets.XCCONFIG_DEV_DEFIYIELD_API_KEY }}
          XCCONFIG_DEV_TWITTER_BEARER_TOKEN: ${{ secrets.XCCONFIG_DEV_TWITTER_BEARER_TOKEN }}
          XCCONFIG_DEV_HS_PROVIDER_API_KEY: ${{ secrets.XCCONFIG_DEV_HS_PROVIDER_API_KEY }}
          XCCONFIG_DEV_WALLET_CONNECT_V2_PROJECT_KEY: ${{ secrets.XCCONFIG_DEV_WALLET_CONNECT_V2_PROJECT_KEY }}
