name: Deploy Dev to AppCenter

on:
  push:
    branches: [ version/* ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy to AppCenter
    runs-on: macos-13

    steps:
      - name: Setup Xcode to 15.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby v3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Setup Rust and Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Lipo via Cargo
        run: cargo install cargo-lipo

      - name: Add iOS targets to Rust
        run: rustup target add aarch64-apple-ios x86_64-apple-ios

      - name: Run Fastlane (build, upload to AppCenter)
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: dev
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          APP_ID: ${{ secrets.APP_ID }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
          APP_CENTER_API_TOKEN: ${{ secrets.APP_CENTER_API_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

          XCCONFIG_DEV_ETHERSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_ETHERSCAN_API_KEY }}
          XCCONFIG_DEV_ARBISCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_ARBISCAN_API_KEY }}
          XCCONFIG_DEV_OPTIMISM_ETHERSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_OPTIMISM_ETHERSCAN_API_KEY }}
          XCCONFIG_DEV_BSCSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_BSCSCAN_API_KEY }}
          XCCONFIG_DEV_POLYGONSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_POLYGONSCAN_API_KEY }}
          XCCONFIG_DEV_SNOWTRACE_API_KEY: ${{ secrets.XCCONFIG_DEV_SNOWTRACE_API_KEY }}
          XCCONFIG_DEV_GNOSISSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_GNOSISSCAN_API_KEY }}
          XCCONFIG_DEV_FTMSCAN_API_KEY: ${{ secrets.XCCONFIG_DEV_FTMSCAN_API_KEY }}
          XCCONFIG_DEV_DEFIYIELD_API_KEY: ${{ secrets.XCCONFIG_DEV_DEFIYIELD_API_KEY }}
          XCCONFIG_DEV_TWITTER_BEARER_TOKEN: ${{ secrets.XCCONFIG_DEV_TWITTER_BEARER_TOKEN }}
          XCCONFIG_DEV_HS_PROVIDER_API_KEY: ${{ secrets.XCCONFIG_DEV_HS_PROVIDER_API_KEY }}
          XCCONFIG_DEV_WALLET_CONNECT_V2_PROJECT_KEY: ${{ secrets.XCCONFIG_DEV_WALLET_CONNECT_V2_PROJECT_KEY }}
          XCCONFIG_DEV_OPEN_SEA_API_KEY: ${{ secrets.XCCONFIG_DEV_OPEN_SEA_API_KEY }}
          XCCONFIG_DEV_TRONGRID_API_KEY: ${{ secrets.XCCONFIG_DEV_TRONGRID_API_KEY }}
          XCCONFIG_DEV_UNSTOPPABLE_DOMAINS_API_KEY: ${{ secrets.XCCONFIG_DEV_UNSTOPPABLE_DOMAINS_API_KEY }}
          XCCONFIG_DEV_ONE_INCH_API_KEY: ${{ secrets.XCCONFIG_DEV_ONE_INCH_API_KEY }}
